# Generated by Django 4.2.16 on 2024-11-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee_interface', '0005_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
