# Generated by Django 4.2.16 on 2024-11-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_client_interface', '0001_initial'),
        ('app_employee_interface', '0006_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_employee_interface.employee')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_employee_interface.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_client_interface.order')),
            ],
        ),
    ]
