# Generated by Django 4.2.16 on 2024-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee_interface', '0007_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
