# Generated by Django 4.2.16 on 2024-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='asdasd',
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
